/**:
  ros__parameters:
    wheel_radius: 0.14 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.05 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 0.6 # between front wheel center and rear wheel center
    wheel_tread: 0.5 # between left wheel center and right wheel center
    front_overhang: 0.15 # between front wheel center and vehicle front
    rear_overhang: 0.25 # between rear wheel center and vehicle rear
    left_overhang: 0.05 # between left wheel center and vehicle left
    right_overhang: 0.05 # between right wheel center and vehicle right
    vehicle_height: 1.45
    max_steer_angle: 0.70 # [rad] 40degree